// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoLsFiknzCNray08qbcgz093gEOAVt--g',
    appId: '1:42162887591:web:b3c131e61c18855fffb482',
    messagingSenderId: '42162887591',
    projectId: 'fitness-7e4ab',
    authDomain: 'fitness-7e4ab.firebaseapp.com',
    storageBucket: 'fitness-7e4ab.firebasestorage.app',
    measurementId: 'G-4HDR5MCGN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnOFJpRbY4j4yg475-CB7OhqUxU4z4UNM',
    appId: '1:42162887591:android:e18a3937eb2e5f5effb482',
    messagingSenderId: '42162887591',
    projectId: 'fitness-7e4ab',
    storageBucket: 'fitness-7e4ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKvQ78adlfgyTaxr4ssPu4e27bquXgs3w',
    appId: '1:42162887591:ios:3219550cda19f323ffb482',
    messagingSenderId: '42162887591',
    projectId: 'fitness-7e4ab',
    storageBucket: 'fitness-7e4ab.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKvQ78adlfgyTaxr4ssPu4e27bquXgs3w',
    appId: '1:42162887591:ios:3219550cda19f323ffb482',
    messagingSenderId: '42162887591',
    projectId: 'fitness-7e4ab',
    storageBucket: 'fitness-7e4ab.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoLsFiknzCNray08qbcgz093gEOAVt--g',
    appId: '1:42162887591:web:5b2a5151d8c1ed3fffb482',
    messagingSenderId: '42162887591',
    projectId: 'fitness-7e4ab',
    authDomain: 'fitness-7e4ab.firebaseapp.com',
    storageBucket: 'fitness-7e4ab.firebasestorage.app',
    measurementId: 'G-KEJNGZVK9K',
  );
}
